### PR TITLE
cEP-0005: Add settings dependent paragraphs

### PR DESCRIPTION
**Pull request by sils**

### CODE REVIEW

**Comment by userzimmermann** [comment]
ack https://github.com/coala/cEPs/pull/34/commits/eca908d1c6154d8e0195f5cdf253039741f0a555

**Comment by userzimmermann** [comment]
unack https://github.com/coala/cEPs/pull/34/commits/eca908d1c6154d8e0195f5cdf253039741f0a555

**Comment by userzimmermann** [comment]
ack https://github.com/coala/cEPs/pull/34/commits/ce21fdfdb7bd9afcd3c295e72fdc306851aba650

**Comment by Makman2** [comment]
ack 49d1af2

**Comment by userzimmermann** [comment]
reack https://github.com/coala/cEPs/commit/49d1af255392a2ce651b8bb9e16a2d5a437b6060

**Comment by userzimmermann** [comment]
@rultor merge

**Pull request merged**
