### PR TITLE
README.md: Add green mode cEP

### PR DESCRIPTION
**Pull request by ishanSrt**

### CODE REVIEW

**Comment by jayvdb** [comment]
Needs rebase

**Comment by ishanSrt** [comment]
rebased @jayvdb

**Review by jayvdb — APPROVED** [review]

**Comment by jayvdb** [comment]
ack https://github.com/coala/cEPs/pull/164/commits/0933fd2a64bf8231ad867c115d73611fe1064887

**Comment by jayvdb** [comment]
Needs rebase again

**Comment by ishanSrt** [comment]
@jayvdb rebased

**Comment by jayvdb** [comment]
ack https://github.com/coala/cEPs/pull/164/commits/0daa94289919d5dff171ce771b24f057c64f33d5

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
