### PR TITLE
cEP-0010.md: Fix a typo

### PR DESCRIPTION
**Pull request by ishanSrt**
Removed Root.Formatting.Quotation.prefered_quotation on line 141
Removed Root.Formatting.FileLength.max_file_length on line 155
Appended max_identifier_length with min_identifier_length on line 194

Closes https://github.com/coala/cEPs/issues/93

### CODE REVIEW

**Review by khanchi97 — APPROVED** [review]
Changes LGTM 👍

**Comment by khanchi97** [comment]
ack 06ba4a4

**Comment by khanchi97** [comment]
unack 06ba4a4

**Comment by khanchi97** [comment]
@ishanSrt I don't know why gitmate didn't show an error in your commit message.But in your commit message, you should use present tense i.e `remove` not `removed`.If you don't know how to change last commit then you can use `git commit --amend` and then push it again to your fork :)

**Comment by ishanSrt** [comment]
I don't understand after amending my commit and pushing it showed me the error message that my tip of the current branch was behind. I tried pull many times but finally had to do a force push

**Comment by khanchi97** [comment]
ack 23f2ed0

**Comment by Makman2** [comment]
> I don't understand after amending my commit and pushing it showed me the error message that my tip of the current branch was behind. I tried pull many times but finally had to do a force push

If you change history (e.g. by amending), you have to force push instead of a normal push. git tries to prevent you from accidentally "loosing" code, but in your case this was desired :+1:

**Comment by Makman2** [comment]
Don't merge yet please, I'm not sure if the underlying issue is valid^^

**Comment by Makman2** [comment]
Commit message @ishanSrt :
Seems we have not enforced it yet, but please write the letter after `:` upper-case in the shortlog.
Also, the commit body is redundant, the diff shows exactly the same ;)

**Comment by Makman2** [comment]
unack 23f2ed0

**Comment by ishanSrt** [comment]
What is ack and unack ?

**Comment by ishanSrt** [comment]
I changed my commit and now I have only fixed a typo and nothing else

**Comment by Makman2** [comment]
@ishanSrt Let's wait for an answer from @khanchi97 what he thinks, as it's his issue^^ We would need to modify the issue^^

**Comment by Makman2** [comment]
In the commit body:
The issue reference should be `Closes ....` instead of `closes: ....` :+1:
Otherwise good to merge

**Comment by Makman2** [comment]
unack 63eab31

**Comment by khanchi97** [comment]
ack 2ee6c17

**Comment by Makman2** [comment]
No colon please after `Closes` ;)

**Comment by Makman2** [comment]
unack 2ee6c17

**Comment by Makman2** [comment]
ack 9bc6768

**Comment by Makman2** [comment]
unack 9bc6768

**Comment by Makman2** [comment]
I've just seen you are using the short-reference variant in `Closes ....`. Please use the full link to the issue instead (so instead of just `#93` put `https://github.com/coala/cEPs/issues/93`)

**Comment by ishanSrt** [comment]
@Makman I have put the full link now although it shows only #93

**Comment by Makman2** [comment]
ack 536242f

**Comment by ishanSrt** [comment]
@Makman2 How can you make out whether I have used a full url or the short-reference?

**Comment by Makman2** [comment]
During manual merge I'm doing `git log`, which does not do GitHub-magic-autolinking ;) There you can see the real plain message :+1:

**Pull request merged**
