### PR TITLE
cEP-009: Change status

### PR DESCRIPTION
**Pull request by satwikkansal**
Changes status to 'active'.

### CODE REVIEW

**Comment by meetmangukiya** [comment]
cEP 9 is already implemented?

**Comment by satwikkansal** [comment]
@meetmangukiya yes

**Comment by meetmangukiya** [comment]
ack 2d8274c

**Comment by adtac** [comment]
@rultor merge

**Comment by adtac** [comment]
ack https://github.com/coala/cEPs/commit/2d8274ca94d1140fc436d5123e3245bdf3ea547a

**Comment by adtac** [comment]
@rultor merge

**Pull request merged**
