### PR TITLE
Improve on aspect tree

### PR DESCRIPTION
**Pull request by AsnelChristian**

### CODE REVIEW

**Review by userzimmermann — CHANGES_REQUESTED** [review]
@Asnelchristian The aspects tree looks really nicer now :) Also `DataClump` is fine! But it needs a bit more explanation in the according commit body. And was `coalaOkay` solely invented by you or also approved by others?

**Comment by userzimmermann** [comment]
ack https://github.com/coala/cEPs/pull/83/commits/89ddc200b725a95cd110c744bd9ae00f9e00bbd4

**Comment by AsnelChristian** [comment]
I made it up on my own, i mean `coalaOkay`

**Comment by AsnelChristian** [comment]
reack https://github.com/coala/cEPs/pull/83/commits/817897c8b8bde1b1102cd0920774aa8cb4f8c294

**Comment by userzimmermann** [comment]
ack https://github.com/coala/cEPs/pull/83/commits/0e5870a2826528fb8d4bd5914e8f5c810072252f

**Review by userzimmermann — COMMENTED** [review]
@Asnelchristian https://github.com/coala/cEPs/pull/83/commits/3f71b29b0831d4e4d1e07a7ccb63f7641c5360b4 is still a bit up to discussion according to https://github.com/coala/coala/pull/4328#issuecomment-306550739

Everything else is just 🎉 :)

**Comment by userzimmermann** [comment]
ack https://github.com/coala/cEPs/pull/83/commits/3f71b29b0831d4e4d1e07a7ccb63f7641c5360b4

**Review by userzimmermann — APPROVED** [review]

**Comment by userzimmermann** [comment]
@rultor merge

**Pull request merged**
