### PR TITLE
cEP-0001: Fix link to newcomer guide

### PR DESCRIPTION
**Pull request by xferra**
Before:
>[newcomer guide](coala.io/newcomer)

After:
>[newcomer guide](//coala.io/newcomer)

Fixes https://github.com/coala/cEPs/issues/109

### CODE REVIEW

**Review by li-boxuan — COMMENTED** [review]
Please follow http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html and revise your commit message. You should mention which issue your PR fixes or closes.

**Comment by xferra** [comment]
@li-boxuan Thank you for the reminder 👍 updated

**Review by li-boxuan — APPROVED** [review]
LGTM 👍

**Review by himanshuc3 — APPROVED** [review]

**Comment by jayvdb** [comment]
We require proper rebasing using git.

**Comment by jayvdb** [comment]
unack https://github.com/coala/cEPs/pull/104/commits/9d545a686a99a4b5f93226eabbcf3f9e2819bc83

**Comment by jayvdb** [comment]
ack https://github.com/coala/cEPs/pull/104/commits/d584d34eb42a45c1656ebdadbdcbc2650051ec80

**Comment by jayvdb** [comment]
discard the top commit, and you can use `@gitmate-bot rebase` to do the dirty work for you, if you want

**Comment by jayvdb** [comment]
cripes. that shouldnt have happened ;-)

**Comment by jayvdb** [comment]
ack https://github.com/coala/cEPs/pull/104/commits/f0c598fef39550e2a92cd521a4ae677180944a21

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
