### PR TITLE
README.md: Add entry for cEP-0025

### PR DESCRIPTION
**Pull request by ankitxjoshi**
Closes https://github.com/coala/cEPs/issues/158

### CODE REVIEW

**Comment by jayvdb** [comment]
Might be better to add them at the end, otherwise we have lots of resizes of the table requiring changes of all lines.

Or maybe change the README to .rst or .asciidoc for a less broken table syntax.
 
(c.f. https://github.com/coala/cEPs/issues/129)

**Review by sangamcse — CHANGES_REQUESTED** [review]
Actually, your column size is exceeding and I think that's the reason it is breaking. Make the column size to 313. 😉

**Comment by ankitxjoshi** [comment]
I know that the column size is exceeding. But can't reduce the content.

**Comment by sangamcse** [comment]
You can remove 2 spaces after GSoC project link
> But can't reduce the content.

**Comment by ankitxjoshi** [comment]
It's the title column that will create problem.

**Comment by ankitxjoshi** [comment]
And I think that we will face the similar problem with rst or asciidoc.

**Comment by sangamcse** [comment]
Maybe we should restrict Title's line length.

**Comment by jayvdb** [comment]
commit message has the wrong filename.

**Review by jayvdb — APPROVED** [review]

**Comment by jayvdb** [comment]
ack https://github.com/coala/cEPs/pull/159/commits/6f483d90c042f39254b33a422646bd1748d03961

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
