### PR TITLE
WIP: cEP-0004: Propose "coala's Interactive UI"

### PR DESCRIPTION
**Pull request by underyx**

### CODE REVIEW

**Comment by underyx** [comment]
@sils how about an exponential backoff for these reminders? 😇

**Comment by sils** [comment]
uhm IMO it's quite nice that they're being so annoying as an open PR will be annoying to reviewers/all sorts of people as well. The options of a good PR are either be active, be reminded every week, or give up and close it. That's better than exponential inactivity IMO.

**Comment by Mariatta** [comment]
Maybe PRs can be automatically closed/abandon after **X** reminders and unassign the issue so others can pick it up 😛

**Comment by sils** [comment]
that idea I like, we had it before. It just always lacks someone to
implement it ;)

**Pull request closed without merging**
