### PR TITLE
cEP-0010.md: Fix spelling error in the heading

### PR DESCRIPTION
**Pull request by Yagya-Chaudhary**
The aspests ---> The aspects

Closes https://github.com/coala/cEPs/issues/90

### CODE REVIEW

**Review by jayvdb — CHANGES_REQUESTED** [review]
fix -> Fix

**Comment by jayvdb** [comment]
ack https://github.com/coala/cEPs/pull/127/commits/bacab77668a0e08f6abe8a8a26f231400b5ef16d

**Review by li-boxuan — APPROVED** [review]
FWIW, you could also change the title of this PR.

**Review by jayvdb — APPROVED** [review]

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
