### PR TITLE
cEP-0005.md: Fix typo

### PR DESCRIPTION
**Pull request by li-boxuan**
analyses --> analysis.

Fixes https://github.com/coala/cEPs/issues/102

### CODE REVIEW

**Review by virresh — CHANGES_REQUESTED** [review]
Hello @li-boxuan ,
Consider using Closes in the commit message than using Fixes 
(Refer http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html#issue-reference )

**Comment by li-boxuan** [comment]
@virresh Hi, thanks! I have changed the commit message.
Btw, I referred to the [Example 3](http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html#more-examples) which uses 'Fixes' in commit message when fixing a typo. Do you think the example should be changed? :)

**Comment by virresh** [comment]
Hey @li-boxuan ,
I just re-read the example and yes, it seems quite misleading (considering the majority of commits about fixing small typos are using Closes, including my newcomer issue :sweat_smile: ). Probably it's a good idea to discuss this in [here](https://gitter.im/coala/documentation) and make an issue regarding this in the documentation repo.

**Comment by li-boxuan** [comment]
@virresh Sure, thanks for your advice.

**Review by virresh — APPROVED** [review]

**Comment by Udayan12167** [comment]
Ack https://github.com/coala/cEPs/pull/103/commits/a752e387ed90fc56ed44770327978bffbfbbdbdf

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
