### PR TITLE
cEP-0006.md: Fix doxing typo

### LINKED ISSUE #100: cEP-0006.md Fix a typo
The correct spelling for `doxing` is `doxxing`

### PR DESCRIPTION
**Pull request by nikhilzac95**
This fixes the typo and changes it from doxing --> doxxing.

Closes https://github.com/coala/cEPs/issues/100

### CODE REVIEW

**Comment by saksham189** [comment]
capital C in closes

**Comment by nikhilzac95** [comment]
@anctartica made changes as told. Please check again.

**Comment by RaiVaibhav** [comment]
ack 00b6d53690b630162cca965b42afaed854cd79f3

**Review by RaiVaibhav — APPROVED** [review]

**Comment by jayvdb** [comment]
ack 00b6d53

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
