### PR TITLE
cEP-0010.md: Update cEP to match existing aspects

### PR DESCRIPTION
**Pull request by pareksha**
This updates cEP according to
the existing aspects.

### CODE REVIEW

**Review by adhikasp — APPROVED** [review]
LGTM :+1:

**Comment by jayvdb** [comment]
commit message `Update cEP` doesnt tell me much

**Comment by pareksha** [comment]
Rest info is in commit body

**Comment by jayvdb** [comment]
The shortlog should be descriptive.

**Comment by jayvdb** [comment]
ack https://github.com/coala/cEPs/pull/147/commits/40be4837e359e522ba3aa808ebb4b39038691b1e

**Review by jayvdb — APPROVED** [review]

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
