### PR TITLE
.gitignore: Add .gitignore

### PR DESCRIPTION
**Pull request by Utkarsh1308**
Add .gitignore file to cEPs

Fixes https://github.com/coala/cEPs/issues/135

### CODE REVIEW

**Comment by saksham189** [comment]
The link to the issue is incorrect

**Comment by Utkarsh1308** [comment]
Oh sorry I don't know where that s came from. Fixing it.

**Review by jayvdb — APPROVED** [review]

**Comment by jayvdb** [comment]
ack 668c450

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
