### PR TITLE
fix link in CoC

### PR DESCRIPTION
**Pull request by obestwalter**

### CODE REVIEW

**Comment by AsnelChristian** [comment]
Nice :+1:

**Comment by AsnelChristian** [comment]
please can you modify your commit message to follow the guidelines provided in https://coala.io/commit

**Comment by obestwalter** [comment]
I could, but I won't - too much overhead for a one char change in a md doc.

**Comment by obestwalter** [comment]
Hi @Asnelchristian, I had to dig my laptop out because I feel guilty now - so I have to at least explain myself a bit more clearly :)

I know that in the time I write this I also would be able to to read those guidelines and produce a commit message that is up to your standards, but I just don't want to. And this is why:

Imagine you walk along the road and someone drops something without noticing. You rush over and pick it up for them. What usually happens is that you get a "thank you", the person takes the item and everyone is moving on with their lives. But now imagine this person refuses to take their item back, but asks you to give it to you with a certain additional gesture instead. To perform that gesture you have to read a little leaflet they try to hand to you. What would you do? We seem to think this kind of thing is o.k. for trivial pull requests, though. I think we should rethink that. I am fully for good processes and we should definitely have them in place and document them, but if somebody passes by and just wants to help you with something they noticed: please just say thank you and clean the thing yourself - they just did you a (very small) favour and that's all there is to it. If that person comes back and wants to provide "real" contributions, I think then is the right time to start educating them about the particular culture and requirements of your project.

No bad feelings - just my two cents.

**Pull request closed without merging**
