### PR TITLE
README.md: Include cEP-0027 in the index table

### PR DESCRIPTION
**Pull request by sangamcse**
This includes the coala Bears Testing API cEP into the
index table.

### CODE REVIEW

**Review by pareksha — CHANGES_REQUESTED** [review]
It would be better to write `BaseTestHelper` class and `GlobalBearTestHelper` class. It looks more precise.

Plus it is also missing the WHY. Include that it is to improve the testing etc.

**Comment by sangamcse** [comment]
Done 👍, @pareksha.

**Review by pareksha — APPROVED** [review]
Nicely done, LGTM :+1:

**Comment by jayvdb** [comment]
ack e2af017

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Review by jayvdb — APPROVED** [review]

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
