### PR TITLE
cEP-0003.md: Updated coala-analyzer to coala

### PR DESCRIPTION
**Pull request by hollamad**
Line number 28 updated the repo name from coala-analyzer to coala

Fixes the issue https://github.com/Madhukar-SH/cEPs.git

### CODE REVIEW

**Comment by techievena** [comment]
Follow guidelines for writing a proper commit message https://coala.io/commit

**Comment by hollamad** [comment]
I have amended the old commit and written it according to the "Writing a good commit" guide.

**Comment by Vamshi99** [comment]
Looks good, just remove about line number in commit message, as it will change on with commmits.

**Comment by hollamad** [comment]
Thank you, I finally learnt how to amend commits :)

**Comment by Vamshi99** [comment]
@Madhukar-SH As you already mentioned about filename in commit head, no need of mentioning in commit message, just write `Change repository name from coala-anlayzer to coala.` in commit message. Then good to go.

**Comment by Vamshi99** [comment]
ack 57cfe06

**Comment by Udayan12167** [comment]
@rultor merge

**Pull request merged**
