### PR TITLE
cEP-0001: Remove BLD

### PR DESCRIPTION
**Pull request by sils**
The concept of the BLD was based on suggestions from several community members requesting centralized leadership at that time.

I believe coala has grown up and that the concept of the BLD is no longer needed.

There is a diverse set of very capable people, maintainers are starting to meet regularly to give coala a clear direction. Our democratic processes are maturing and our community is able to make better decisions than a single person could do.

### CODE REVIEW

**Comment by NiklasMM** [comment]
Would it make sense to replace the BLD with an elected project leader? Just to have someone who can make executive decisions if the need arises and act as a tie breaker when the community is split.

**Comment by sils** [comment]
@NiklasMM the BLD powers were never used and I don't think we need one single project leader. We have teams and team leaders as a formalization but even that is optional, many people including you are taking the initiative and do great things, why should there be an uber leader to make them feel smaller than they are?

**Comment by sims1253** [comment]
They were used ;)
I vote for this pr to be blocked until my pr is merged...

**Comment by jayvdb** [comment]
Imo this should be closed until the teams are operating much better, and there is a maintainer decision that we are ready.
At the moment, this role is a nice safety value, and i believe it helps the teams become established.
We did need the BLD to step in to resolve the CoC problem we had, and ensure it was dealt with properly.

**Comment by sils** [comment]
@jayvdb what do you think of @NiklasMM s proposal to elect the BLD?

**Comment by jayvdb** [comment]
@sils, I think the politics created by elections are not worth elections atm.  And teams havent really maintained momentum, so there is no 'next' level.  Maintainer meetings are also not a stable thing yet, unable to finalise todo items using group decision mechanisms.

I feel that at the moment, we're best with a mostly flat system, and you as the safety value, if there is a serious conflict.

Our second CoC problem was resolved in an adhoc manner, without properly using the CoC mechanisms, and done without a BLD override, but there wasnt really a 'split' in the community.  There was a little uncertainty in how to deal with the problem initially, but once the risk became better known, several maintainers acted in their area to analyse and/or close down the problem asap.  That is a flat system working, and it needs a stable unpolitical BLD for maintainers to feel confident to act quickly.

Closing as this is quite stale.  If a change is required, a group discussion is needed to find a new solution.

**Pull request closed without merging**
