### PR TITLE
cEP-0006.md: Fix doxing typo

### LINKED ISSUE #100: cEP-0006.md Fix a typo
The correct spelling for `doxing` is `doxxing`

### PR DESCRIPTION
**Pull request by nikhilzac95**
This fixes the typo and changes it from doxing --> doxxing.

closes https://github.com/coala/cEPs/issues/100

### CODE REVIEW

**Review by manankalra — COMMENTED** [review]
change Fixes -> fixes in the commit body
Also, remove the colon after *Fixes*

**Review by manankalra — COMMENTED** [review]
And use *Closes* instead of *Fixes*

**Comment by saksham189** [comment]
you are not following the commit guidelines. Refer to this: http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html

**Comment by saksham189** [comment]
`Closes` starting from a newline

**Pull request closed without merging**
