### PR TITLE
Typo fixed - 'doxing' changed to 'doxxing'

### LINKED ISSUE #100: cEP-0006.md Fix a typo
The correct spelling for `doxing` is `doxxing`

### PR DESCRIPTION
**Pull request by nikhilzac95**
**cEP-0006.md**: Fix _doxing_ typo

This fixes the typo and changes
it from **doxing** --> **doxxing**.

Fixes : https://github.com/coala/cEPs/issues/100

### CODE REVIEW

**Comment by Vamshi99** [comment]
Follow commit guidelines, coala.io/commit

**Comment by nikhilzac95** [comment]
necessary changes have been made to the commit message

**Comment by Vamshi99** [comment]
you have edited the PR message, whereas you should edit commit message and head. Refer http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html#editing-commit-messages

**Comment by nikhilzac95** [comment]
will do this again.

**Pull request closed without merging**
